FROM node:24-alpine

RUN apk upgrade --no-cache libcrypto3 libssl3

WORKDIR /web

COPY web/certs/netskope-ca.pem /web/certs/netskope-ca.pem
ENV NODE_EXTRA_CA_CERTS=/web/certs/netskope-ca.pem

COPY web/package.json web/package-lock.json web/nuxt.config.ts web/tsconfig.json ./
COPY web/app ./app
RUN npm ci

COPY web/ .

ENV HOST=0.0.0.0
ENV PORT=3000
ENV NUXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]
